/**
 * MLEngine.js — local machine learning for C. elegans developmental timing.
 *
 * Approach (no server required):
 *  1. "Correction model" — learns per-stage timing correction factors from
 *     real-world observations vs simulated predictions. Simple weighted mean.
 *  2. "Contribution package" — anonymized JSON export ready for sharing
 *     or server-side aggregation (federated learning without the server).
 *  3. "Community import" — loads aggregated correction factors from a
 *     researcher-provided JSON file (can be generated by merging packages).
 *
 * Correction factor storage: localStorage key 'wt_ml_corrections'
 * Format: { "N2:20": { egg:1.0, l1:0.98, l2:1.05, ... }, ... }
 */

import { RealWorldData } from './RealWorldData.js?v=152';
import { getStages }     from './LifeCycle.js?v=152';

const CORR_KEY = 'wt_ml_corrections';

export class MLEngine {
  constructor() {
    this._corrections = this._load();
    this._trainingLog = [];  // in-memory log of training runs
  }

  // ── Training ───────────────────────────────────────────────────────────────

  /**
   * Learn correction factors from all plates that have real-world data.
   * @param {object[]} plates  active + bin plates
   * @returns {TrainingResult}
   */
  train(plates) {
    const allFactors = {};   // key: "strainId:tempC" → {stageId: [factors]}
    let totalPoints = 0;

    for (const plate of plates) {
      const realData = RealWorldData.get(plate.id);
      if (!realData?.length) continue;

      const stages  = getStages(plate.strainId, plate.tempC);
      const factors = RealWorldData.correctionFactors(realData, stages);
      const key     = `${plate.strainId}:${plate.tempC}`;

      if (!allFactors[key]) allFactors[key] = {};
      for (const [stageId, f] of Object.entries(factors)) {
        if (!allFactors[key][stageId]) allFactors[key][stageId] = [];
        allFactors[key][stageId].push(f);
        totalPoints++;
      }
    }

    // Average the factors
    const corrections = {};
    for (const [key, stageMap] of Object.entries(allFactors)) {
      corrections[key] = {};
      for (const [stageId, vals] of Object.entries(stageMap)) {
        const avg = vals.reduce((a, b) => a + b, 0) / vals.length;
        // Clamp: don't let correction go too extreme (0.5× – 2.0×)
        corrections[key][stageId] = Math.max(0.5, Math.min(2.0, avg));
      }
    }

    this._corrections = corrections;
    this._persist();

    const entry = { timestamp: Date.now(), totalPoints, keys: Object.keys(corrections) };
    this._trainingLog.push(entry);

    return {
      success: true,
      totalPoints,
      strainsLearned: Object.keys(corrections).length,
      corrections,
      summary: `Learned from ${totalPoints} observations across ${Object.keys(corrections).length} strain/temp combination(s).`,
    };
  }

  /**
   * Apply learned correction to a predicted stage hour.
   * Returns original value if no correction data available.
   */
  correctHours(strainId, tempC, stageId, predictedHours) {
    const key    = `${strainId}:${tempC}`;
    const factor = this._corrections[key]?.[stageId] ?? 1.0;
    return predictedHours * factor;
  }

  /** Get all correction factors (for display). */
  getCorrections() { return { ...this._corrections }; }

  hasTrained() { return Object.keys(this._corrections).length > 0; }

  resetCorrections() { this._corrections = {}; this._persist(); }

  // ── Export ─────────────────────────────────────────────────────────────────

  /**
   * Export a contribution package — anonymized, ready to share with a
   * researcher who can aggregate data from multiple users.
   */
  exportContributionPackage(plates) {
    const pkg = {
      version:    '1.0',
      format:     'wormtrace-contribution',
      exported_at: new Date().toISOString(),
      platform:   'WormTrace PWA',
      anonymized: true,
      note: 'Upload to researcher for federated averaging. No personal data included.',
      plates: [],
      correction_model: this._corrections,
      training_log: this._trainingLog.slice(-10),
    };

    for (const plate of plates) {
      const realData = RealWorldData.get(plate.id);
      if (!realData?.length) continue;

      const stages  = getStages(plate.strainId, plate.tempC);
      const devs    = RealWorldData.computeDeviations(realData, stages);
      const factors = RealWorldData.correctionFactors(realData, stages);

      pkg.plates.push({
        strain: plate.strainId,
        tempC:  plate.tempC,
        worm_count: plate.wormCount ?? 1,
        initial_food_ml: plate.initialFood ?? 0.5,
        observation_count: realData.length,
        observations: realData.map(p => ({
          time_hours:     p.time_hours,
          stage_observed: p.stage_observed,
          worm_length_um: p.worm_length_um,
          food_pct:       p.food_pct,
          // strip free-text notes for privacy
        })),
        derived_corrections: factors,
        deviations: devs.map(d => ({
          time_hours:    d.time_hours,
          sim_stage:     d.sim_stage_id,
          real_stage:    d.stage_observed,
          matches:       d.matches_sim,
          correction:    +d.correction.toFixed(4),
          deviation_hrs: +d.deviation_hrs.toFixed(2),
        })),
      });
    }

    return pkg;
  }

  /**
   * Export as ML training dataset (JSON) suitable for external model training
   * with TensorFlow/PyTorch/scikit-learn.
   */
  exportTrainingDataset(plates) {
    const dataset = {
      version:    '1.0',
      format:     'wormtrace-ml-dataset',
      exported_at: new Date().toISOString(),
      description: 'C. elegans developmental timing dataset from WormTrace PWA.',
      columns: ['strain_id','temp_c','time_hours','stage_observed','worm_length_um',
                'food_pct','eggs_counted','sim_stage_id','correction_factor'],
      strain_encoding: { N2:0, 'dpy-13':1, 'daf-2':2, 'daf-16':3, 'eat-2':4, 'age-1':5 },
      temp_values: [10, 15, 20, 25],
      stage_encoding: { egg:0, l1:1, l2:2, l3:3, l4:4, young_adult:5, adult:6, dauer:7 },
      rows: [],
    };

    for (const plate of plates) {
      const realData = RealWorldData.get(plate.id);
      if (!realData?.length) continue;
      const stages = getStages(plate.strainId, plate.tempC);
      const devs   = RealWorldData.computeDeviations(realData, stages);
      for (const d of devs) {
        dataset.rows.push([
          plate.strainId, plate.tempC, d.time_hours,
          d.stage_observed, d.worm_length_um ?? '',
          d.food_pct ?? '', d.eggs_counted ?? 0,
          d.sim_stage_id, +d.correction.toFixed(4),
        ]);
      }
    }

    return dataset;
  }

  /**
   * Import community-aggregated correction factors (provided by researcher).
   * Merges with local corrections using weighted average.
   */
  importCommunityPackage(json) {
    const pkg = typeof json === 'string' ? JSON.parse(json) : json;
    const incoming = pkg.correction_model ?? pkg.corrections ?? {};
    let merged = 0;

    for (const [key, stageMap] of Object.entries(incoming)) {
      if (!this._corrections[key]) {
        this._corrections[key] = { ...stageMap };
      } else {
        // Simple average merge
        for (const [stageId, factor] of Object.entries(stageMap)) {
          const local = this._corrections[key][stageId] ?? 1.0;
          this._corrections[key][stageId] = (local + factor) / 2;
          merged++;
        }
      }
    }

    this._persist();
    return { merged, keys: Object.keys(incoming) };
  }

  // ── Internal ───────────────────────────────────────────────────────────────
  _load() {
    try { return JSON.parse(localStorage.getItem(CORR_KEY) || '{}'); } catch { return {}; }
  }
  _persist() {
    try { localStorage.setItem(CORR_KEY, JSON.stringify(this._corrections)); } catch {}
  }
}
