// AUTO-GENERATED from c_elegans_lifespan_full_variables_curated.xlsx (2026-06-03).
// Regenerate from the sheet; do not hand-edit. Imported worms for the Worm Collection.
// lifespanDays = parsed midpoint of sheet mean (null if "Not standardized"/"Varies").
// dafClass = mapped dauer phenotype (wild | daf-c | daf-d | "" if undetermined).
export const WORM_CATALOG = [
  {
    "id": "imp_pd1074",
    "name": "PD1074",
    "stock": "PD1074",
    "gene": "",
    "allele": "",
    "genotype": "N2-derived reference isolate",
    "mutation": "N2-derived reference isolate",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Near N2 expected",
    "curveShape": "Expected N2-like; verify experimentally",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Normal/expected",
    "category": "Control/reference",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Reference genome strain",
    "notes": "Use as genomic reference background; lifespan should be measured side-by-side with N2 if important. · Needs strain-specific lifespan cross-check",
    "refs": "WormBase/CGC strain records",
    "url": "https://wormbase.org/species/c_elegans/strain/WBStrain00030553",
    "confidence": "Medium",
    "color": "#f97316",
    "source": "imported"
  },
  {
    "id": "imp_cb4856",
    "name": "CB4856",
    "stock": "CB4856",
    "gene": "",
    "allele": "",
    "genotype": "Wild isolate, Hawaii",
    "mutation": "Wild isolate, Hawaii",
    "pathway": "",
    "lifespanDays": 18,
    "lifespanText": "15-20",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~0.8-1.0x",
    "curveShape": "Often N2-like but can shift by environment",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Natural variation; not a standard dauer mutant",
    "category": "Wild isolate/natural variation",
    "background": "CB4856",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "High polymorphism vs N2; QTL mapping",
    "notes": "Use for mapping/natural variation; lifespan values are less standardized than N2/daf-2. · Needs assay-specific confirmation",
    "refs": "Natural variation literature; CGC",
    "url": "https://cgc.umn.edu/strain/CB4856",
    "confidence": "Medium",
    "color": "#22d3ee",
    "source": "imported"
  },
  {
    "id": "imp_daf2e1368",
    "name": "DR1572 (e1368)",
    "stock": "DR1572",
    "gene": "daf-2",
    "allele": "e1368",
    "genotype": "daf-2(e1368) III",
    "mutation": "daf-2(e1368)",
    "pathway": "",
    "lifespanDays": 38,
    "lifespanText": "30-45",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~1.5-2.2x",
    "curveShape": "Delayed survival decline",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "daf-c",
    "dauerClass": "Dauer-constitutive (Daf-c)",
    "dauerText": "Dauer constitutive / temp-sensitive",
    "category": "Aging/dauer",
    "background": "N2-derived",
    "tempC": "20 preferred",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Reduced IIS; long-lived",
    "notes": "Good daf-2 allele, but cite the exact paper used for numerical lifespan. · Verified phenotype; exact lifespan needs source-specific value",
    "refs": "CGC + daf-2 literature",
    "url": "https://cgc.umn.edu/strain/DR1572",
    "confidence": "High",
    "color": "#a3e635",
    "source": "imported"
  },
  {
    "id": "imp_eat2ad1116",
    "name": "DA1116 (ad1116)",
    "stock": "DA1116 / eat-2(ad1116)",
    "gene": "eat-2",
    "allele": "ad1116",
    "genotype": "eat-2(ad1116) II",
    "mutation": "eat-2(ad1116)",
    "pathway": "",
    "lifespanDays": 30,
    "lifespanText": "25-35",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~1.2-1.7x",
    "curveShape": "Moderately delayed decline",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primarily dauer",
    "category": "Dietary restriction/aging",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Reduced pharyngeal pumping; DR-like longevity",
    "notes": "Not equivalent to all forms of dietary restriction; phenotype depends on food conditions. · Verified DR-like longevity",
    "refs": "eat-2 lifespan literature",
    "url": "https://cgc.umn.edu/strain/DA1116",
    "confidence": "High",
    "color": "#e879f9",
    "source": "imported"
  },
  {
    "id": "imp_mq130",
    "name": "MQ130",
    "stock": "MQ130",
    "gene": "",
    "allele": "",
    "genotype": "sir-2.1 overexpression line",
    "mutation": "sir-2.1 overexpression line",
    "pathway": "",
    "lifespanDays": 30,
    "lifespanText": "25-35",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~1.2-1.7x reported",
    "curveShape": "Moderately delayed, but debated",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer mutant",
    "category": "Aging/sirtuin",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Reported lifespan extension in some studies",
    "notes": "Sirtuin longevity effects have background/assay concerns; do not use as hard benchmark without direct paper. · Tag as debated / needs primary confirmation",
    "refs": "sir-2.1 lifespan literature",
    "url": "https://wormbase.org/species/c_elegans/gene/WBGene00004707",
    "confidence": "Medium",
    "color": "#fb7185",
    "source": "imported"
  },
  {
    "id": "imp_clk1e2519",
    "name": "MQ887 (e2519)",
    "stock": "MQ887 / clk-1(e2519)",
    "gene": "clk-1",
    "allele": "e2519",
    "genotype": "clk-1(e2519) III",
    "mutation": "clk-1(e2519)",
    "pathway": "",
    "lifespanDays": 30,
    "lifespanText": "25-35",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~1.2-1.7x",
    "curveShape": "Delayed with developmental effects",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Mitochondrial aging",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Altered ubiquinone biosynthesis; slow development; long-lived",
    "notes": "Developmental delay can confound lifespan interpretation if age synchronization is poor. · Verified long-lived phenotype; exact values vary",
    "refs": "clk-1 longevity papers",
    "url": "https://cgc.umn.edu/strain/MQ887",
    "confidence": "High",
    "color": "#38bdf8",
    "source": "imported"
  },
  {
    "id": "imp_isp1qm150",
    "name": "MQ887 (qm150)",
    "stock": "MQ887? / isp-1(qm150)",
    "gene": "isp-1",
    "allele": "qm150",
    "genotype": "isp-1(qm150) IV",
    "mutation": "isp-1(qm150)",
    "pathway": "",
    "lifespanDays": 32,
    "lifespanText": "25-40",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~1.3-2.0x",
    "curveShape": "Delayed decline; often long right tail",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Mitochondrial aging",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Complex III Rieske iron-sulfur protein mutant; long-lived",
    "notes": "I am not fully certain on exact strain stock name for qm150; verify CGC row before ordering/citing. · Verified gene/phenotype; strain name must be verified",
    "refs": "isp-1 longevity literature",
    "url": "https://wormbase.org/species/c_elegans/gene/WBGene00002267",
    "confidence": "High",
    "color": "#facc15",
    "source": "imported"
  },
  {
    "id": "imp_mev1kn1",
    "name": "TK22 (kn1)",
    "stock": "TK22",
    "gene": "mev-1",
    "allele": "kn1",
    "genotype": "mev-1(kn1) III",
    "mutation": "mev-1(kn1)",
    "pathway": "",
    "lifespanDays": 12,
    "lifespanText": "10-15",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~0.5-0.8x",
    "curveShape": "Early steep decline",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Stress/mitochondrial",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Succinate dehydrogenase cytochrome b subunit mutant; oxidative stress sensitive",
    "notes": "Useful positive control for oxidative damage sensitivity. · Verified short-lived/stress-sensitive phenotype",
    "refs": "mev-1 literature",
    "url": "https://cgc.umn.edu/strain/TK22",
    "confidence": "High",
    "color": "#4ade80",
    "source": "imported"
  },
  {
    "id": "imp_hsf1sy441",
    "name": "PS3551 (sy441)",
    "stock": "PS3551",
    "gene": "hsf-1",
    "allele": "sy441",
    "genotype": "hsf-1(sy441) I",
    "mutation": "hsf-1(sy441)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Short-lived reported",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "<1.0x",
    "curveShape": "Earlier decline",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Proteostasis/aging",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Heat-shock factor mutant; stress/proteostasis defects",
    "notes": "Use as stress/proteostasis strain; lifespan numeric values should be paper-specific. · Needs exact lifespan source",
    "refs": "hsf-1 literature/CGC",
    "url": "https://cgc.umn.edu/strain/PS3551",
    "confidence": "Medium",
    "color": "#c084fc",
    "source": "imported"
  },
  {
    "id": "imp_skn1zu67",
    "name": "EU1 (zu67)",
    "stock": "EU1",
    "gene": "skn-1",
    "allele": "zu67",
    "genotype": "skn-1(zu67) IV / allele-specific",
    "mutation": "skn-1(zu67)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "12-18 reported depending allele",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "~0.6-0.9x",
    "curveShape": "Earlier decline expected",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Developmental effects; not primarily dauer",
    "category": "Oxidative stress/aging",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Nrf-like transcription factor pathway; oxidative stress regulation",
    "notes": "SKN-1 has essential/developmental roles; exact strain/allele matters a lot. · Needs allele-specific confirmation",
    "refs": "skn-1 literature",
    "url": "https://wormbase.org/species/c_elegans/gene/WBGene00004804",
    "confidence": "Medium",
    "color": "#fca5a5",
    "source": "imported"
  },
  {
    "id": "imp_eri1mg366",
    "name": "GR1307 (mg366)",
    "stock": "GR1307",
    "gene": "eri-1",
    "allele": "mg366",
    "genotype": "eri-1(mg366) IV",
    "mutation": "eri-1(mg366)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Must measure directly",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not lifespan model by default",
    "category": "RNAi tool",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "HT115 common for RNAi",
    "sampleN": "Varies",
    "phenotype": "Enhanced RNAi sensitivity",
    "notes": "Tag any lifespan value as experimental unless measured in your assay. · Not a lifespan benchmark",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/GR1307",
    "confidence": "Low",
    "color": "#2dd4bf",
    "source": "imported"
  },
  {
    "id": "imp_rrf3pk1426",
    "name": "NL2099 (pk1426)",
    "stock": "NL2099",
    "gene": "rrf-3",
    "allele": "pk1426",
    "genotype": "rrf-3(pk1426) II",
    "mutation": "rrf-3(pk1426)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Must measure directly",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not lifespan model by default",
    "category": "RNAi tool",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "HT115 common for RNAi",
    "sampleN": "Varies",
    "phenotype": "Enhanced RNAi sensitivity",
    "notes": "Use for RNAi screens; include its own control survival curve. · Not a lifespan benchmark",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/NL2099",
    "confidence": "Low",
    "color": "#fdba74",
    "source": "imported"
  },
  {
    "id": "imp_glp1e2141",
    "name": "CF512 (e2141)",
    "stock": "CF512",
    "gene": "glp-1",
    "allele": "e2141",
    "genotype": "glp-1(e2141) III",
    "mutation": "glp-1(e2141)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Long-lived under germline-ablation conditions",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": ">1.0x",
    "curveShape": "Delayed if germline eliminated",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Reproduction/aging",
    "background": "N2-derived",
    "tempC": "25 often used for sterility induction",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Temperature-sensitive germline-defective; long-lived under restrictive conditions",
    "notes": "Cannot compare to 20°C N2 without explaining temp-shift and sterility protocol. · Condition-dependent; exact protocol required",
    "refs": "glp-1 longevity literature",
    "url": "https://cgc.umn.edu/strain/CF512",
    "confidence": "Medium",
    "color": "#93c5fd",
    "source": "imported"
  },
  {
    "id": "imp_tj356",
    "name": "TJ356",
    "stock": "TJ356",
    "gene": "",
    "allele": "",
    "genotype": "zIs356 [daf-16p::daf-16a/b::GFP + rol-6]",
    "mutation": "zIs356 [daf-16p::daf-16a/b::GFP + rol-6]",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Measure if using lifespan",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Reporter",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "DAF-16::GFP nuclear localization under stress/IIS changes",
    "notes": "Use for localization, not as lifespan control unless you assay lifespan directly. · Reporter verified; lifespan not benchmarked here",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/TJ356",
    "confidence": "Low",
    "color": "#f472b6",
    "source": "imported"
  },
  {
    "id": "imp_cl2166",
    "name": "CL2166",
    "stock": "CL2166",
    "gene": "",
    "allele": "",
    "genotype": "dvIs19 [gst-4p::GFP::NLS]",
    "mutation": "dvIs19 [gst-4p::GFP::NLS]",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Measure if using lifespan",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Reporter",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "gst-4::GFP induction under oxidative/xenobiotic stress",
    "notes": "Good for paraquat/juglone/toxin response; do not cite a generic lifespan number. · Reporter verified; lifespan not benchmark",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/CL2166",
    "confidence": "Low",
    "color": "#bef264",
    "source": "imported"
  },
  {
    "id": "imp_sj4100",
    "name": "SJ4100",
    "stock": "SJ4100",
    "gene": "",
    "allele": "",
    "genotype": "zcIs13 [hsp-6p::GFP]",
    "mutation": "zcIs13 [hsp-6p::GFP]",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Measure if using lifespan",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Reporter",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Mitochondrial unfolded protein response reporter",
    "notes": "Use fluorescence readout for UPRmt, not as lifespan benchmark. · Reporter verified; lifespan not benchmark",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/SJ4100",
    "confidence": "Low",
    "color": "#67e8f9",
    "source": "imported"
  },
  {
    "id": "imp_sj4005",
    "name": "SJ4005",
    "stock": "SJ4005",
    "gene": "",
    "allele": "",
    "genotype": "zcIs4 [hsp-4p::GFP]",
    "mutation": "zcIs4 [hsp-4p::GFP]",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Measure if using lifespan",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Reporter",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "ER unfolded protein response reporter",
    "notes": "Use for ER stress/UPRER assays. · Reporter verified; lifespan not benchmark",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/SJ4005",
    "confidence": "Low",
    "color": "#d8b4fe",
    "source": "imported"
  },
  {
    "id": "imp_da2123",
    "name": "DA2123",
    "stock": "DA2123",
    "gene": "",
    "allele": "",
    "genotype": "adIs2122 [lgg-1p::GFP::LGG-1 + rol-6]",
    "mutation": "adIs2122 [lgg-1p::GFP::LGG-1 + rol-6]",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Measure if using lifespan",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Reporter",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Autophagosome/autophagy reporter",
    "notes": "Autophagy reporter, but GFP::LGG-1 puncta require careful interpretation. · Reporter verified; lifespan not benchmark",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/DA2123",
    "confidence": "Low",
    "color": "#86efac",
    "source": "imported"
  },
  {
    "id": "imp_unc119",
    "name": "NL5901 (+)",
    "stock": "NL5901",
    "gene": "unc-119",
    "allele": "+",
    "genotype": "pkIs2386 [unc-54p::alpha-synuclein::YFP + unc-119(+)]",
    "mutation": "unc-119(+)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Disease-model survival may differ; assay directly",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Disease model",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Human alpha-synuclein aggregation in body-wall muscle",
    "notes": "Use for aggregation/toxicity readouts; do not use generic lifespan value. · Reporter/disease phenotype verified; lifespan uncertain",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/NL5901",
    "confidence": "Low",
    "color": "#fecaca",
    "source": "imported"
  },
  {
    "id": "imp_cl2006",
    "name": "CL2006",
    "stock": "CL2006",
    "gene": "",
    "allele": "",
    "genotype": "dvIs2 [unc-54p::human Abeta1-42 + rol-6]",
    "mutation": "dvIs2 [unc-54p::human Abeta1-42 + rol-6]",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Often shorter/healthspan affected",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "Condition-specific",
    "curveShape": "Earlier functional decline expected",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Disease model",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Constitutive Abeta expression in muscle; paralysis phenotype",
    "notes": "Better track paralysis curve separately from death survival curve. · Disease phenotype verified; lifespan numeric needs source",
    "refs": "Abeta C. elegans model papers/CGC",
    "url": "https://cgc.umn.edu/strain/CL2006",
    "confidence": "Medium",
    "color": "#5eead4",
    "source": "imported"
  },
  {
    "id": "imp_smg1cc546ts",
    "name": "CL4176 (cc546ts)",
    "stock": "CL4176",
    "gene": "smg-1",
    "allele": "cc546ts",
    "genotype": "smg-1(cc546ts); dvIs27 [myo-3p::Abeta1-42 + rol-6]",
    "mutation": "smg-1(cc546ts)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Paralysis model, not standard lifespan strain",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "Not appropriate as generic survival",
    "curveShape": "Paralysis curve after temperature shift",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Disease model",
    "background": "N2-derived",
    "tempC": "16 then 25 often used",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Temperature-inducible Abeta; rapid paralysis after upshift",
    "notes": "Track percent unparalyzed vs time after temperature upshift. · Do not treat as normal lifespan curve",
    "refs": "CL4176 papers/CGC",
    "url": "https://cgc.umn.edu/strain/CL4176",
    "confidence": "High for paralysis; Low for lifespan",
    "color": "#fb923c",
    "source": "imported"
  },
  {
    "id": "imp_am141",
    "name": "AM141",
    "stock": "AM141",
    "gene": "",
    "allele": "",
    "genotype": "rmIs133 [unc-54p::Q40::YFP]",
    "mutation": "rmIs133 [unc-54p::Q40::YFP]",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Aggregation/healthspan curve, not generic survival",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "wild",
    "dauerClass": "Facultative (stress-induced)",
    "dauerText": "Not primary dauer",
    "category": "Disease/proteostasis model",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Polyglutamine Q40 aggregation in muscle",
    "notes": "Use aggregate counts/motility as primary endpoint.",
    "refs": "https://cgc.umn.edu/strain/AM141",
    "url": "Low",
    "confidence": "Reporter phenotype verified; lifespan uncertain",
    "color": "#a5b4fc",
    "source": "imported"
  },
  {
    "id": "imp_daf16m26",
    "name": "DR26 (m26)",
    "stock": "DR26",
    "gene": "daf-16",
    "allele": "m26",
    "genotype": "daf-16(m26) I",
    "mutation": "daf-16(m26)",
    "pathway": "",
    "lifespanDays": 2,
    "lifespanText": "Shorter than N2 / suppressor role",
    "medianText": "Varies",
    "maxText": "Varies",
    "relN2": "<1.0x expected",
    "curveShape": "Early or N2-like depending context",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "daf-d",
    "dauerClass": "Dauer-defective (Daf-d)",
    "dauerText": "Dauer defective",
    "category": "Dauer/IIS",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "DAF-16 loss; dauer-defective and suppresses daf-2 longevity",
    "notes": "Use allele-specific data; do not mix with daf-16(mu86) values. · Phenotype verified; exact lifespan needs source",
    "refs": "CGC/WormBase",
    "url": "https://cgc.umn.edu/strain/DR26",
    "confidence": "Medium",
    "color": "#f9a8d4",
    "source": "imported"
  },
  {
    "id": "imp_daf12sa204",
    "name": "JK1107 (sa204)",
    "stock": "JK1107",
    "gene": "daf-12",
    "allele": "sa204",
    "genotype": "daf-12(sa204) X",
    "mutation": "daf-12(sa204)",
    "pathway": "",
    "lifespanDays": null,
    "lifespanText": "Not standardized",
    "medianText": "Not standardized",
    "maxText": "Not standardized",
    "relN2": "Unknown",
    "curveShape": "Must assay directly",
    "broodSize": null,
    "eggToAdultH": null,
    "dafClass": "daf-d",
    "dauerClass": "Dauer-defective (Daf-d)",
    "dauerText": "Dauer defective/abnormal depending conditions",
    "category": "Dauer/nuclear receptor",
    "background": "N2-derived",
    "tempC": "20",
    "foodSource": "OP50 typical",
    "sampleN": "Varies",
    "phenotype": "Dauer signaling/nuclear hormone receptor mutant",
    "notes": "Use for dauer experiments more than lifespan benchmark.",
    "refs": "https://cgc.umn.edu/strain/JK1107",
    "url": "Low",
    "confidence": "Dauer phenotype relevant; lifespan uncertain",
    "color": "#fde047",
    "source": "imported"
  }
];
